[package]
name = "transfer-role-features"
version = "0.0.0"
authors = ["Dorin Marian Iancu <dorin.iancu@multiversx.com>"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[features]
debug = ["multiversx-sc-scenario", "vault/debug", "multiversx-sc-modules/debug"]

[dev-dependencies.vault]
path = "../vault"

[dependencies.multiversx-sc]
version = "0.43.3"
path = "../../../../framework/base"

[dependencies.multiversx-sc-modules]
version = "0.43.3"
path = "../../../../contracts/modules"

[dependencies.multiversx-sc-scenario]
version = "0.43.3"
path = "../../../../framework/scenario"
optional = true

[dev-dependencies.transfer-role-features]
path = "."
features = ["debug"]
