[package]
name = "digital-cash"
version = "0.0.0"
authors = [ "Valentin Craciun"]
edition = "2021"
publish = false

[lib]
path = "src/digital_cash.rs"

[features]
debug = ["multiversx-sc-scenario"]

[dependencies.multiversx-sc]
version = "0.43.3"
path = "../../../framework/base"

[dependencies.multiversx-sc-scenario]
version = "0.43.3"
path = "../../../framework/scenario"
optional = true

[dev-dependencies.digital-cash]
path = "."
features = ["debug"]
