[package]
name = "kitty-auction"
version = "0.0.0"
authors = [ "dorin-iancu <dorin.iancu@multiversx.com>",]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[features]
debug = ["multiversx-sc-scenario"]

[dependencies.kitty]
version = "0.0.0"
path = "../common/kitty"

[dependencies.kitty-ownership]
version = "0.0.0"
path = "../kitty-ownership"

[dependencies.multiversx-sc]
version = "0.43.3"
path = "../../../../framework/base"

[dependencies.multiversx-sc-scenario]
version = "0.43.3"
path = "../../../../framework/scenario"
optional = true

[dev-dependencies.kitty-auction]
path = "."
features = ["debug"]
