[package]
name = "rust-testing-framework-tester"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@multiversx.com>"]
edition = "2021"
publish = false

[features]
debug = ["multiversx-sc-scenario", "vault/debug", "adder/debug", "basic-features/debug", "forwarder/debug"]

[dependencies.multiversx-sc-scenario]
version = "0.43.3"
path = "../../../framework/scenario"
optional = true

[dependencies.multiversx-sc]
version = "0.43.3"
path = "../../../framework/base"
features = [ "alloc" ]

[dev-dependencies.adder]
path = "../../examples/adder"

[dev-dependencies.basic-features]
path = "../../feature-tests/basic-features"

[dev-dependencies.rust-testing-framework-tester]
path = "."
features = ["debug"]

[dev-dependencies]
num-bigint = "0.4.2"
num-traits = "0.2"
hex = "0.4"

[dev-dependencies.forwarder]
path = "../composability/forwarder"

[dev-dependencies.vault]
path = "../composability/vault"
