[package]
name = "proxy-test-second"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@multiversx.com>"]
edition = "2021"
publish = false

[lib]
path = "src/proxy-test-second.rs"

[features]
debug = ["multiversx-sc-scenario"]

[dependencies.multiversx-sc]
version = "0.43.3"
path = "../../../../framework/base"
features = ["alloc"]

[dependencies.multiversx-sc-scenario]
version = "0.43.3"
path = "../../../../framework/scenario"
optional = true

[dev-dependencies.proxy-test-second]
path = "."
features = ["debug"]
