[package]
name = "lottery-esdt"
version = "0.0.0"
authors = [ "Dorin Iancu <dorin.iancu@multiversx.com>",]
edition = "2021"
publish = false

[lib]
path = "src/lottery.rs"

[features]
debug = ["multiversx-sc-scenario"]

[dependencies.multiversx-sc]
version = "0.43.3"
path = "../../../framework/base"

[dependencies.multiversx-sc-scenario]
version = "0.43.3"
path = "../../../framework/scenario"
optional = true

[dev-dependencies.lottery-esdt]
path = "."
features = ["debug"]
