[package]
name = "alloc-features"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@multiversx.com>"]
edition = "2021"
publish = false

[lib]
path = "src/alloc_features_main.rs"

[features]
debug = ["multiversx-sc-scenario"]

[dependencies.multiversx-sc]
version = "0.43.3"
path = "../../../framework/base"
features = ["alloc"]

[dependencies.multiversx-sc-scenario]
version = "0.43.3"
path = "../../../framework/scenario"
optional = true

[dev-dependencies.alloc-features]
path = "."
features = ["debug"]

[dev-dependencies.esdt-system-sc-mock]
path = "../esdt-system-sc-mock"
