[package]
name = "token-release"
version = "0.0.1"
authors = [ "you",]
edition = "2021"
publish = false

[lib]
path = "src/token_release.rs"

[features]
debug = ["multiversx-sc-scenario"]

[dependencies.multiversx-sc]
version = "0.43.3"
path = "../../../framework/base"

[dependencies.multiversx-sc-scenario]
version = "0.43.3"
path = "../../../framework/scenario"
optional = true

[dev-dependencies.token-release]
path = "."
features = ["debug"]

