[package]
name = "linked-list-repeat"
version = "0.0.0"
authors = ["Claudiu-Marcel Bruda <claudiu.bruda@multiversx.com>"]
edition = "2021"
publish = false

[lib]
path = "src/linked_list_repeat.rs"

[features]
debug = ["multiversx-sc-scenario"]

[dependencies.benchmark-common]
path = "../benchmark-common"

[dependencies.multiversx-sc]
version = "0.43.3"
path = "../../../../framework/base"

[dependencies.multiversx-sc-scenario]
version = "0.43.3"
path = "../../../../framework/scenario"
optional = true

[dev-dependencies.linked-list-repeat]
path = "."
features = ["debug"]
